import {useEffect,useState} from 'react';
import MainLayout from '../layouts/MainLayout';
import api from '../api/axios';
import {Plus,Search,RefreshCw,Building2} from 'lucide-react';
const empty={client_code:'',company_name:'',gst_number:'',billing_address:'',branch:'',gst_region:'',billing_cycle:'Monthly',contact_person:'',contact_email:'',contact_phone:'',credit_terms_days:30,is_active:true};
export default function Clients(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{const r=await api.get('/erp/clients');setRows(r.data||[])}catch(e){setError(e.response?.data?.detail||'Unable to load clients')}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 const filtered=rows.filter(x=>[x.client_code,x.company_name,x.gst_number,x.contact_person,x.branch].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())));
 async function save(e){e.preventDefault();setSaving(true);try{await api.post('/erp/clients',form);setOpen(false);setForm(empty);await load()}catch(e){setError(e.response?.data?.detail||'Unable to create client')}finally{setSaving(false)}}
 return <MainLayout><div className="space-y-5"><div className="flex justify-between gap-3"><div><h1 className="text-2xl font-black text-white">Client Accounts</h1><p className="text-xs text-slate-400 mt-1">Client master, GST, billing and contact controls.</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-cyan-400 text-slate-950 font-bold text-xs"><Plus className="w-4 h-4"/> Add Client</button></div>
 <div className="flex gap-2"><div className="flex-1 relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company, code, GST, contact..." className="w-full cyber-input pl-9"/></div><button onClick={load} className="px-3 rounded-xl border border-slate-800 text-slate-300"><RefreshCw className="w-4 h-4"/></button></div>{error&&<div className="p-3 rounded-xl border border-red-500/30 bg-red-500/10 text-red-300 text-xs">{error}</div>}
 <div className="cyber-panel rounded-2xl border border-slate-800 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-900/70 text-slate-400"><tr>{['Client','Code','GST','Contact','Phone','Billing','Status'].map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="7" className="px-4 py-10 text-center text-slate-500">Loading clients...</td></tr>:filtered.map(x=><tr key={x.id} className="border-t border-slate-800/70"><td className="px-4 py-3"><div className="flex items-center gap-2"><Building2 className="w-4 h-4 text-cyan-300"/><div><b className="text-white">{x.company_name}</b><div className="text-[10px] text-slate-500">{x.branch||'No branch'}</div></div></div></td><td className="px-4 py-3 text-cyan-300">{x.client_code||'—'}</td><td className="px-4 py-3">{x.gst_number||'—'}</td><td className="px-4 py-3">{x.contact_person||'—'}</td><td className="px-4 py-3">{x.contact_phone||'—'}</td><td className="px-4 py-3">{x.billing_cycle||'—'} / {x.credit_terms_days}d</td><td className="px-4 py-3 text-emerald-300">{x.is_active?'Active':'Inactive'}</td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan="7" className="px-4 py-10 text-center text-slate-500">No clients found.</td></tr>}</tbody></table></div>
 {open&&<div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><form onSubmit={save} className="w-full max-w-2xl cyber-panel border border-slate-700 rounded-2xl p-6 space-y-4"><h2 className="text-lg font-black text-white">Add Client</h2><div className="grid md:grid-cols-2 gap-3">{[['client_code','Client Code'],['company_name','Company Name'],['gst_number','GST Number'],['branch','Branch'],['gst_region','GST Region'],['billing_cycle','Billing Cycle'],['contact_person','Contact Person'],['contact_email','Email'],['contact_phone','Phone']].map(([k,l])=><label className="text-xs text-slate-300" key={k}>{l}<input required={k==='company_name'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full cyber-input mt-1"/></label>)}</div><label className="text-xs text-slate-300">Billing Address<textarea value={form.billing_address} onChange={e=>setForm({...form,billing_address:e.target.value})} className="w-full cyber-input mt-1"/></label><label className="text-xs text-slate-300">Credit Terms (days)<input type="number" value={form.credit_terms_days} onChange={e=>setForm({...form,credit_terms_days:Number(e.target.value)})} className="w-full cyber-input mt-1"/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="px-4 py-2 border border-slate-800 rounded-xl text-slate-300">Cancel</button><button disabled={saving} className="px-4 py-2 rounded-xl bg-cyan-400 text-slate-950 font-bold">{saving?'Saving...':'Create Client'}</button></div></form></div>}</div></MainLayout>
}