import {useEffect,useState} from 'react';
import MainLayout from '../layouts/MainLayout';
import api from '../api/axios';
import {Plus,Search,RefreshCw,Building2,Users,ChevronRight,X} from 'lucide-react';
import {useAuth} from '../context/useAuth';
const empty={client_code:'',company_name:'',gst_number:'',billing_address:'',branch:'',gst_region:'',billing_cycle:'Monthly',contact_person:'',contact_email:'',contact_phone:'',credit_terms_days:30,is_active:true,field_officer_ids:[]};
export default function Clients(){
 const {user}=useAuth(),canManage=['OWNER','SUPER_ADMIN','ADMIN'].includes(user?.role);
 const [rows,setRows]=useState([]),[officers,setOfficers]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[detail,setDetail]=useState(null),[form,setForm]=useState(empty),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{const r=await api.get('/erp/clients');setRows(r.data||[]);if(canManage){const e=await api.get('/erp/employees');setOfficers((e.data||[]).filter(x=>!String(x.category||'').toLowerCase().includes('guard')))}}catch(e){setError(e.response?.data?.detail||'Unable to load clients')}finally{setLoading(false)}}
 useEffect(()=>{load()},[canManage]);
 const filtered=rows.filter(x=>[x.client_code,x.company_name,x.gst_number,x.contact_person,x.branch,x.field_officers].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())));
 async function openDetail(client){try{const r=await api.get('/erp/clients/'+client.id);setDetail(r.data)}catch(e){setError(e.response?.data?.detail||'Unable to load client details')}}
 async function save(e){e.preventDefault();setSaving(true);try{await api.post('/erp/clients',form);setOpen(false);setForm(empty);await load()}catch(e){setError(e.response?.data?.detail||'Unable to create client')}finally{setSaving(false)}}
 return <MainLayout><div className="space-y-5">
  <div className="flex justify-between gap-3"><div><h1 className="text-2xl font-black text-slate-900">Client Accounts</h1><p className="text-xs text-slate-500 mt-1">Client master, billing, contacts and field-officer deployment.</p></div>{canManage&&<button onClick={()=>setOpen(true)} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-teal-600 text-white font-bold text-xs"><Plus className="w-4 h-4"/> Add Client</button>}</div>
  <div className="flex gap-2"><div className="flex-1 relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company, code, GST, contact, field officer..." className="w-full h-10 rounded-xl border border-slate-200 bg-white px-9 text-sm outline-none focus:border-teal-400"/></div><button onClick={load} className="px-3 rounded-xl border border-slate-200 bg-white text-slate-500"><RefreshCw className="w-4 h-4"/></button></div>
  {error&&<div className="p-3 rounded-xl border border-red-200 bg-red-50 text-red-700 text-xs">{error}</div>}
  <div className="bg-white rounded-2xl border border-slate-200 overflow-x-auto shadow-sm"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Client','Field Officer(s)','GST','Contact','Billing','Status',''].map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="7" className="px-4 py-10 text-center text-slate-400">Loading clients...</td></tr>:filtered.map(x=><tr key={x.id} onClick={()=>openDetail(x)} className="border-t border-slate-100 hover:bg-slate-50 cursor-pointer"><td className="px-4 py-3"><div className="flex items-center gap-2"><Building2 className="w-4 h-4 text-teal-600"/><div><b className="text-slate-900">{x.company_name}</b><div className="text-[10px] text-slate-400">{x.client_code||'No code'}</div></div></div></td><td className="px-4 py-3"><div className="flex items-center gap-1.5 text-slate-600"><Users className="w-3.5 h-3.5 text-teal-600"/>{x.field_officers||'Not assigned'}</div></td><td className="px-4 py-3">{x.gst_number||'—'}</td><td className="px-4 py-3">{x.contact_person||'—'}</td><td className="px-4 py-3">{x.billing_cycle||'—'} / {x.credit_terms_days}d</td><td className="px-4 py-3 text-emerald-600">{x.is_active?'Active':'Inactive'}</td><td className="px-4 py-3"><ChevronRight className="w-4 h-4 text-slate-400"/></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan="7" className="px-4 py-10 text-center text-slate-400">No clients found.</td></tr>}</tbody></table></div>
  {open&&<div className="fixed inset-0 z-50 bg-slate-950/50 flex items-center justify-center p-4"><form onSubmit={save} className="w-full max-w-3xl bg-white border border-slate-200 rounded-2xl p-6 space-y-4 shadow-2xl max-h-[90vh] overflow-y-auto"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-slate-900">Add Client</h2><p className="text-xs text-slate-500 mt-1">Assign one or more field officers to this client.</p></div><button type="button" onClick={()=>setOpen(false)}><X className="w-5 h-5 text-slate-400"/></button></div><div className="grid md:grid-cols-2 gap-3">{['client_code','company_name','gst_number','branch','gst_region','billing_cycle','contact_person','contact_email','contact_phone'].map(k=><label className="text-xs text-slate-600 capitalize" key={k}>{k.replaceAll('_',' ')}<input required={k==='company_name'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full h-10 rounded-lg border border-slate-200 px-3 mt-1 text-sm"/></label>)}</div><label className="text-xs text-slate-600">Billing Address<textarea value={form.billing_address} onChange={e=>setForm({...form,billing_address:e.target.value})} className="w-full rounded-lg border border-slate-200 px-3 py-2 mt-1 text-sm"/></label><label className="text-xs text-slate-600">Credit Terms (days)<input type="number" value={form.credit_terms_days} onChange={e=>setForm({...form,credit_terms_days:Number(e.target.value)})} className="w-full h-10 rounded-lg border border-slate-200 px-3 mt-1 text-sm"/></label><div><p className="text-xs font-semibold text-slate-700 mb-2">Deploy Field Officer(s)</p><div className="grid sm:grid-cols-2 gap-2 max-h-44 overflow-y-auto border border-slate-200 rounded-xl p-2">{officers.length?officers.map(o=><label key={o.id} className="flex items-center gap-2 p-2 rounded-lg hover:bg-slate-50 cursor-pointer"><input type="checkbox" checked={form.field_officer_ids.includes(o.id)} onChange={e=>setForm({...form,field_officer_ids:e.target.checked?[...form.field_officer_ids,o.id]:form.field_officer_ids.filter(id=>id!==o.id)})}/><span className="text-xs"><b className="text-slate-800">{o.name}</b><span className="text-slate-400"> • {o.designation||o.category||'Employee'}</span></span></label>):<p className="text-xs text-slate-400 p-2">No eligible field employees found.</p>}</div></div><div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="px-4 py-2 border border-slate-200 rounded-xl text-slate-600">Cancel</button><button disabled={saving} className="px-4 py-2 rounded-xl bg-teal-600 text-white font-bold">{saving?'Saving...':'Create Client'}</button></div></form></div>}
  {detail&&<div className="fixed inset-0 z-50 bg-slate-950/50 flex items-center justify-center p-4"><div className="w-full max-w-2xl bg-white rounded-2xl p-6 shadow-2xl max-h-[90vh] overflow-y-auto"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-widest text-teal-600 font-bold">Client Profile</p><h2 className="text-2xl font-black text-slate-900 mt-1">{detail.company_name}</h2><p className="text-sm text-slate-500">{detail.contact_person||'No contact'} • {detail.contact_phone||'No phone'}</p></div><button onClick={()=>setDetail(null)}><X className="w-5 h-5 text-slate-400"/></button></div><div className="grid sm:grid-cols-2 gap-3 mt-6"><div className="p-4 rounded-xl bg-slate-50"><p className="text-xs text-slate-400">GST</p><p className="font-semibold text-slate-800 mt-1">{detail.gst_number||'—'}</p></div><div className="p-4 rounded-xl bg-slate-50"><p className="text-xs text-slate-400">Billing</p><p className="font-semibold text-slate-800 mt-1">{detail.billing_cycle||'—'} / {detail.credit_terms_days} days</p></div><div className="sm:col-span-2 p-4 rounded-xl bg-slate-50"><p className="text-xs text-slate-400">Field Officers</p><p className="font-semibold text-slate-800 mt-1">{detail.field_officers||'Not assigned'}</p></div><div className="sm:col-span-2 p-4 rounded-xl bg-slate-50"><p className="text-xs text-slate-400">Billing Address</p><p className="font-semibold text-slate-800 mt-1">{detail.billing_address||'—'}</p></div></div></div></div>}
 </div></MainLayout>
}