import { useEffect, useState } from 'react';
import MainLayout from '../layouts/MainLayout';
import api from '../api/axios';
import { Plus, Search, RefreshCw, UserRound } from 'lucide-react';

const empty = { employee_code:'', name:'', phone:'', designation:'Security Guard', branch:'', joining_date:'', status:'active', emergency_contact:'' };

export default function Employees() {
  const [rows,setRows]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [search,setSearch]=useState(''), [open,setOpen]=useState(false), [form,setForm]=useState(empty), [saving,setSaving]=useState(false);
  async function load() { setLoading(true); setError(''); try { const r=await api.get('/erp/employees'); setRows(r.data||[]); } catch(e) { setError(e.response?.data?.detail||'Unable to load employees'); } finally { setLoading(false); } }
  useEffect(()=>{load()},[]);
  const filtered=rows.filter(x=>[x.employee_code,x.name,x.phone,x.designation,x.branch].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())));
  async function save(e) { e.preventDefault(); setSaving(true); setError(''); try { await api.post('/erp/employees',form); setOpen(false); setForm(empty); await load(); } catch(e) { setError(e.response?.data?.detail||'Unable to create employee'); } finally { setSaving(false); } }
  return <MainLayout><div className="space-y-5">
    <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><h1 className="text-2xl font-black text-white">Employees & HR</h1><p className="text-xs text-slate-400 mt-1">Employee master, deployment identity and workforce status.</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-cyan-400 text-slate-950 font-bold text-xs"><Plus className="w-4 h-4"/> Add Employee</button></div>
    <div className="flex gap-2"><div className="flex-1 relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search code, name, phone, designation..." className="w-full cyber-input pl-9"/></div><button onClick={load} className="px-3 rounded-xl border border-slate-800 text-slate-300"><RefreshCw className="w-4 h-4"/></button></div>
    {error&&<div className="p-3 rounded-xl border border-red-500/30 bg-red-500/10 text-red-300 text-xs">{error}</div>}
    <div className="cyber-panel rounded-2xl border border-slate-800 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-900/70 text-slate-400"><tr>{['Employee','Code','Phone','Designation','Branch','Status','Joined'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>
    {loading?<tr><td colSpan="7" className="px-4 py-10 text-center text-slate-500">Loading workforce...</td></tr>:filtered.map(x=><tr key={x.id} className="border-t border-slate-800/70 hover:bg-slate-900/40"><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg bg-cyan-500/10 flex items-center justify-center text-cyan-300"><UserRound className="w-4 h-4"/></div><div><div className="font-bold text-white">{x.name}</div><div className="text-[10px] text-slate-500">{x.id}</div></div></div></td><td className="px-4 py-3 font-mono text-cyan-300">{x.employee_code}</td><td className="px-4 py-3 text-slate-300">{x.phone}</td><td className="px-4 py-3 text-slate-300">{x.designation||'—'}</td><td className="px-4 py-3 text-slate-300">{x.branch||'—'}</td><td className="px-4 py-3"><span className="px-2 py-1 rounded-lg bg-emerald-500/10 text-emerald-300">{x.status}</span></td><td className="px-4 py-3 text-slate-400">{x.joining_date||'—'}</td></tr>)}
    {!loading&&!filtered.length&&<tr><td colSpan="7" className="px-4 py-10 text-center text-slate-500">No employees found.</td></tr>}</tbody></table></div>
    {open&&<div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><form onSubmit={save} className="w-full max-w-2xl cyber-panel border border-slate-700 rounded-2xl p-6 space-y-4"><div className="flex justify-between"><div><h2 className="text-lg font-black text-white">Add Employee</h2><p className="text-xs text-slate-500">Creates the master record in Supabase.</p></div><button type="button" onClick={()=>setOpen(false)} className="text-slate-400">✕</button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{[['employee_code','Employee Code'],['name','Full Name'],['phone','Phone'],['designation','Designation'],['branch','Branch'],['joining_date','Joining Date'],['emergency_contact','Emergency Contact']].map(([k,l])=><label key={k} className="text-xs text-slate-300">{l}<input required={['employee_code','name','phone'].includes(k)} type={k==='joining_date'?'date':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full cyber-input mt-1"/></label>)}</div><label className="text-xs text-slate-300">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="w-full cyber-input mt-1 bg-slate-900"><option value="active">Active</option><option value="inactive">Inactive</option><option value="terminated">Terminated</option></select></label>{error&&<div className="text-xs text-red-300">{error}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="px-4 py-2 rounded-xl border border-slate-800 text-slate-300">Cancel</button><button disabled={saving} className="px-4 py-2 rounded-xl bg-cyan-400 text-slate-950 font-bold">{saving?'Saving...':'Create Employee'}</button></div></form></div>}
  </div></MainLayout>
}