import { useEffect,useState } from 'react';
import MainLayout from '../layouts/MainLayout';
import api from '../api/axios';
import { Calculator, Download, Lock, RefreshCw } from 'lucide-react';
export default function PayrollView(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[rows,setRows]=useState([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 const load=async()=>{try{setRows((await api.get('/erp/payroll',{params:{month}})).data||[])}catch(e){setMsg(e.response?.data?.detail||'Unable to load payroll')}};
 useEffect(()=>{load()},[month]);
 const calculate=async()=>{setLoading(true);try{const r=await api.post('/erp/payroll/calculate',{month});setMsg(r.data.employees_processed+' employees calculated; '+r.data.salary_holds+' held.');await load()}catch(e){setMsg(e.response?.data?.detail||'Payroll calculation failed')}finally{setLoading(false)}};
 const hold=async(id)=>{const reason=window.prompt('Hold reason: Missing Police Verification / Absconding / Pending Uniform Cost / Manual Flag','Manual Flag');if(!reason)return;const note=window.prompt('Mandatory audit note');if(!note)return;try{await api.post('/erp/payroll/'+id+'/hold',{reason,audit_note:note});await load()}catch(e){setMsg(e.response?.data?.detail||'Salary hold failed')}};
 const pdf=async(id,code)=>{const r=await api.get('/erp/payroll/slips/'+id+'/pdf',{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='salary-slip-'+code+'.pdf';a.click();URL.revokeObjectURL(url)};
 return <MainLayout><div className='space-y-5'><div className='flex justify-between items-center'><div><h1 className='text-2xl font-black text-slate-900'>Statutory Payroll</h1><p className='text-xs text-slate-500 mt-1'>Attendance-driven PF, ESIC, LWF, Uniform EMI, salary holds and payslips.</p></div><div className='flex gap-2'><input type='month' value={month} onChange={e=>setMonth(e.target.value)} className='h-10 border border-slate-200 rounded-xl px-3'/><button onClick={calculate} disabled={loading} className='h-10 px-4 rounded-xl bg-teal-600 text-white font-bold flex gap-2 items-center'><Calculator className='w-4 h-4'/>{loading?'Calculating...':'Calculate Payroll'}</button><button onClick={load} className='p-2 rounded-xl border border-slate-200'><RefreshCw className='w-4 h-4'/></button></div></div>{msg&&<div className='p-3 rounded-xl bg-slate-50 border border-slate-200 text-xs'>{msg}</div>}<div className='bg-white border border-slate-200 rounded-2xl overflow-auto shadow-sm'><table className='w-full text-xs'><thead className='bg-slate-50'><tr>{['Employee','Present','OT','Gross','PF','ESIC','LWF','Uniform','Net','Status','Actions'].map(h=><th key={h} className='p-3 text-left'>{h}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id} className='border-t border-slate-100'><td className='p-3'><b>{x.name}</b><div className='text-[10px] text-slate-400'>{x.employee_code}</div></td><td className='p-3'>{x.present_days}</td><td className='p-3'>{x.overtime_hours}</td><td className='p-3'>{x.gross_pay}</td><td className='p-3'>{x.pf}</td><td className='p-3'>{x.esic}</td><td className='p-3'>{x.lwf}</td><td className='p-3'>{x.uniform_emi}</td><td className='p-3 font-bold'>{x.net_pay}</td><td className='p-3'><span className={x.lifecycle_status==='HELD'?'text-red-600 font-bold':'text-emerald-600'}>{x.lifecycle_status}</span></td><td className='p-3 flex gap-1'><button onClick={()=>pdf(x.id,x.employee_code)} title='Download payslip' className='p-2 rounded-lg border'><Download className='w-3.5 h-3.5'/></button><button onClick={()=>hold(x.id)} title='Place salary hold' className='p-2 rounded-lg border'><Lock className='w-3.5 h-3.5'/></button></td></tr>)}{!rows.length&&<tr><td colSpan='11' className='p-10 text-center text-slate-400'>No payroll slips calculated for this month.</td></tr>}</tbody></table></div></div></MainLayout>;
}