alter table public.sites add column if not exists branch_region varchar(30);
alter table public.sites add constraint sites_branch_region_chk
  check (branch_region is null or branch_region in ('UTTARAKHAND','UTTAR_PRADESH','DELHI_NCR'));

alter table public.invoices
  add column if not exists cgst numeric(12,2) not null default 0,
  add column if not exists sgst numeric(12,2) not null default 0,
  add column if not exists igst numeric(12,2) not null default 0,
  add column if not exists clearance_status text not null default 'PENDING';

create table if not exists public.finance_expenses (
  id bigint generated by default as identity primary key,
  client_id integer references public.clients(id) on delete set null,
  expense_date date not null default current_date,
  category text not null,
  description text,
  amount numeric(12,2) not null default 0 check (amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_finance_expenses_client_date on public.finance_expenses(client_id,expense_date);
alter table public.finance_expenses enable row level security;
drop policy if exists deny_finance_expenses_api on public.finance_expenses;
create policy deny_finance_expenses_api on public.finance_expenses for all to anon, authenticated using (false) with check (false);
