alter table public.clients
  add column if not exists gstin varchar(15),
  add column if not exists branch_region varchar(30),
  add column if not exists contract_start_date date,
  add column if not exists contract_end_date date;

update public.clients
set gstin = gst_number
where gstin is null and gst_number is not null;

alter table public.clients
  add constraint clients_gstin_format_chk
  check (gstin is null or gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$');

alter table public.clients
  add constraint clients_branch_region_chk
  check (branch_region is null or branch_region in ('UTTARAKHAND','UTTAR_PRADESH','DELHI_NCR'));

create table if not exists public.client_contracts (
  id bigint generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  contract_number text not null unique,
  contract_start_date date not null,
  contract_end_date date not null,
  billing_cycle text not null default 'MONTHLY',
  credit_terms_days integer not null default 30,
  wage_indexation_percent numeric(7,3) not null default 0,
  status text not null default 'ACTIVE' check (status in ('DRAFT','ACTIVE','EXPIRED','RENEWED','TERMINATED')),
  renewal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (contract_end_date >= contract_start_date)
);

create index if not exists idx_client_contracts_client on public.client_contracts(client_id);
create index if not exists idx_client_contracts_end_date on public.client_contracts(contract_end_date);

create table if not exists public.site_rate_cards (
  id bigint generated by default as identity primary key,
  site_id integer not null references public.sites(id) on delete cascade,
  vertical text not null check (vertical in ('SECURITY','HOUSEKEEPING','NURSING')),
  category text not null,
  hourly_rate numeric(12,2) not null default 0,
  daily_rate numeric(12,2) not null default 0,
  wage_indexation_percent numeric(7,3) not null default 0,
  effective_from date not null default current_date,
  effective_to date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(site_id, vertical, category, effective_from),
  check (effective_to is null or effective_to >= effective_from)
);

create index if not exists idx_site_rate_cards_site on public.site_rate_cards(site_id);
create index if not exists idx_site_rate_cards_vertical on public.site_rate_cards(vertical,category);

alter table public.sites
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists geofence_radius_meters integer not null default 100;

alter table public.sites
  add constraint sites_geofence_radius_chk check (geofence_radius_meters > 0 and geofence_radius_meters <= 1000);

alter table public.client_contracts enable row level security;
alter table public.site_rate_cards enable row level security;
drop policy if exists deny_client_contracts_api on public.client_contracts;
create policy deny_client_contracts_api on public.client_contracts for all to anon, authenticated using (false) with check (false);
drop policy if exists deny_site_rate_cards_api on public.site_rate_cards;
create policy deny_site_rate_cards_api on public.site_rate_cards for all to anon, authenticated using (false) with check (false);