create table if not exists public.user_permissions (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  permission_key varchar(120) not null,
  allowed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, permission_key)
);

create index if not exists ix_user_permissions_user_id on public.user_permissions(user_id);
create index if not exists ix_user_permissions_permission_key on public.user_permissions(permission_key);
alter table public.user_permissions enable row level security;
