create table if not exists public.payroll_runs (
  id bigint generated by default as identity primary key,
  payroll_month date not null unique,
  status text not null default 'DRAFT' check (status in ('DRAFT','CALCULATED','APPROVED','DISBURSED')),
  calculated_at timestamptz,
  approved_at timestamptz,
  disbursed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.salary_slips (
  id bigint generated by default as identity primary key,
  payroll_run_id bigint not null references public.payroll_runs(id) on delete cascade,
  employee_id uuid not null references public.employees(id) on delete cascade,
  present_days numeric(8,2) not null default 0,
  regular_hours numeric(10,2) not null default 0,
  overtime_hours numeric(10,2) not null default 0,
  basic numeric(12,2) not null default 0,
  hra numeric(12,2) not null default 0,
  allowances numeric(12,2) not null default 0,
  overtime_pay numeric(12,2) not null default 0,
  night_shift_allowance numeric(12,2) not null default 0,
  gross_pay numeric(12,2) not null default 0,
  pf numeric(12,2) not null default 0,
  esic numeric(12,2) not null default 0,
  lwf numeric(12,2) not null default 0,
  uniform_emi numeric(12,2) not null default 0,
  total_deductions numeric(12,2) not null default 0,
  net_pay numeric(12,2) not null default 0,
  lifecycle_status text not null default 'CALCULATED' check (lifecycle_status in ('DRAFT','CALCULATED','APPROVED','DISBURSED','HELD')),
  hold_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(payroll_run_id, employee_id)
);

create table if not exists public.salary_holds (
  id bigint generated by default as identity primary key,
  salary_slip_id bigint not null references public.salary_slips(id) on delete cascade,
  reason text not null,
  audit_note text not null,
  created_by bigint,
  created_at timestamptz not null default now(),
  released_at timestamptz
);

create index if not exists idx_payroll_runs_month on public.payroll_runs(payroll_month);
create index if not exists idx_salary_slips_employee on public.salary_slips(employee_id);
create index if not exists idx_salary_slips_status on public.salary_slips(lifecycle_status);

alter table public.payroll_runs enable row level security;
alter table public.salary_slips enable row level security;
alter table public.salary_holds enable row level security;
drop policy if exists deny_payroll_runs_api on public.payroll_runs;
create policy deny_payroll_runs_api on public.payroll_runs for all to anon, authenticated using (false) with check (false);
drop policy if exists deny_salary_slips_api on public.salary_slips;
create policy deny_salary_slips_api on public.salary_slips for all to anon, authenticated using (false) with check (false);
drop policy if exists deny_salary_holds_api on public.salary_holds;
create policy deny_salary_holds_api on public.salary_holds for all to anon, authenticated using (false) with check (false);
